import type { IntelligenceSourceDefinition } from "@/lib/intelligence/contracts";

export const intelligenceSources = [
  {
    feedFormat: "rss",
    feedUrl: "https://feeds.bbci.co.uk/news/world/rss.xml",
    homepageUrl: "https://www.bbc.com/news/world",
    id: "bbc-world",
    institution: "bbc",
    kind: "journalism",
    name: "BBC World",
    priority: 10,
    topic: "geopolitics",
  },
  {
    feedFormat: "rss",
    feedUrl: "https://www.theguardian.com/world/rss",
    homepageUrl: "https://www.theguardian.com/world",
    id: "guardian-world",
    institution: "guardian",
    kind: "journalism",
    name: "The Guardian World",
    priority: 20,
    topic: "geopolitics",
  },
  {
    feedFormat: "rss",
    feedUrl: "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
    homepageUrl: "https://news.un.org/en/",
    id: "united-nations-world",
    institution: "united-nations",
    kind: "official",
    name: "UN News",
    priority: 30,
    topic: "geopolitics",
  },
  {
    feedFormat: "rss",
    feedUrl: "https://feeds.bbci.co.uk/news/business/rss.xml",
    homepageUrl: "https://www.bbc.com/news/business",
    id: "bbc-business",
    institution: "bbc",
    kind: "journalism",
    name: "BBC Business",
    priority: 40,
    topic: "global-economy",
  },
  {
    feedFormat: "rss",
    feedUrl: "https://www.theguardian.com/uk/business/rss",
    homepageUrl: "https://www.theguardian.com/business",
    id: "guardian-business",
    institution: "guardian",
    kind: "journalism",
    name: "The Guardian Business",
    priority: 50,
    topic: "business-and-industry",
  },
  {
    feedFormat: "rss",
    feedUrl: "https://feeds.bbci.co.uk/news/technology/rss.xml",
    homepageUrl: "https://www.bbc.com/news/technology",
    id: "bbc-technology",
    institution: "bbc",
    kind: "journalism",
    name: "BBC Technology",
    priority: 60,
    topic: "technology-and-ai",
  },
  {
    feedFormat: "rss",
    feedUrl: "https://www.ecb.europa.eu/rss/press.html",
    homepageUrl: "https://www.ecb.europa.eu/press/html/index.en.html",
    id: "ecb-policy-and-media",
    institution: "ecb",
    kind: "official",
    name: "European Central Bank",
    priority: 70,
    topic: "monetary-policy",
  },
  {
    feedFormat: "atom",
    feedUrl:
      "https://ec.europa.eu/eurostat/en/search?_estatsearchportlet_WAR_estatsearchportlet_collection=CAT_PREREL&_estatsearchportlet_WAR_estatsearchportlet_theme=PER_ECOFIN&p_p_id=estatsearchportlet_WAR_estatsearchportlet&p_p_lifecycle=2&p_p_mode=view&p_p_resource_id=atom&p_p_state=maximized",
    homepageUrl: "https://ec.europa.eu/eurostat/news/euro-indicators",
    id: "eurostat-economy-and-finance",
    institution: "eurostat",
    kind: "official",
    name: "Eurostat Economy and Finance",
    priority: 80,
    topic: "spain-and-eu",
  },
  {
    feedFormat: "atom",
    feedUrl:
      "https://ec.europa.eu/eurostat/en/search?_estatsearchportlet_WAR_estatsearchportlet_collection=CAT_PREREL&_estatsearchportlet_WAR_estatsearchportlet_theme=PER_EXTTRA&p_p_id=estatsearchportlet_WAR_estatsearchportlet&p_p_lifecycle=2&p_p_mode=view&p_p_resource_id=atom&p_p_state=maximized",
    homepageUrl:
      "https://ec.europa.eu/eurostat/web/international-trade-in-goods",
    id: "eurostat-international-trade",
    institution: "eurostat",
    kind: "official",
    name: "Eurostat International Trade",
    priority: 90,
    topic: "international-trade",
  },
  {
    feedFormat: "rss",
    feedUrl: "https://www.federalreserve.gov/feeds/press_monetary.xml",
    homepageUrl: "https://www.federalreserve.gov/newsevents/pressreleases.htm",
    id: "federal-reserve-monetary-policy",
    institution: "federal-reserve",
    kind: "official",
    name: "Federal Reserve Monetary Policy",
    priority: 100,
    topic: "monetary-policy",
  },
] as const satisfies readonly IntelligenceSourceDefinition[];
