import type { CourseSystemDefinition } from "./course-system-definition";

export const universityCourseSystems = [
  {
    cameraPosition: [-3, 1.2, -4.2],
    displayName: "Logistics & Distribution",
    id: "logistics",
    labelPosition: {
      compact: [24, 49],
      desktop: [32, 49],
      portrait: [25, 49],
    },
    name: "Logistics and Distribution",
    palette: {
      core: "#f3fbff",
      halo: "#78c8ff",
      orbit: "#79aeea",
    },
    position: [-3, 1, -8.4],
    schedule: [
      {
        day: "monday",
        endTime: "18:30",
        group: "M41",
        room: "E133",
        startTime: "16:30",
      },
      {
        day: "wednesday",
        endTime: "18:30",
        group: "M41",
        room: "E121",
        startTime: "16:30",
      },
    ],
    scale: 1,
    seed: 81_732,
    sourceName: "Distribución Logística",
    status: "explorable",
  },
  {
    cameraPosition: [0, 1.15, -4.4],
    displayName: "Business Ethics",
    id: "business-ethics",
    labelPosition: {
      compact: [77, 49],
      desktop: [68, 49],
      portrait: [76, 49],
    },
    name: "International Business Ethics",
    palette: {
      core: "#edf6ff",
      halo: "#9895d8",
      orbit: "#7778aa",
    },
    position: [0, 1, -8.8],
    schedule: [
      {
        day: "monday",
        endTime: "20:30",
        group: "M41",
        room: "E123",
        startTime: "18:30",
      },
      {
        day: "tuesday",
        endTime: "20:30",
        group: "M41",
        room: "E125",
        startTime: "18:30",
      },
    ],
    scale: 0.86,
    seed: 26_104,
    sourceName: "Ética en los Negocios Internacionales",
    status: "explorable",
  },
  {
    cameraPosition: [-0.3, -0.45, -4.6],
    displayName: "Language A III",
    id: "language-a-iii",
    labelPosition: {
      compact: [71, 69],
      desktop: [66, 72],
      portrait: [68, 70],
    },
    name: "Language A III",
    palette: {
      core: "#eefeff",
      halo: "#64bac8",
      orbit: "#548a96",
    },
    position: [-0.3, -0.7, -9],
    schedule: [
      {
        day: "tuesday",
        endTime: "16:30",
        group: "M33",
        room: "E132",
        startTime: "14:30",
      },
      {
        day: "friday",
        endTime: "16:30",
        group: "M33",
        room: "E032",
        startTime: "14:30",
      },
    ],
    scale: 0.78,
    seed: 59_133,
    sourceName: "Idioma A III",
    status: "explorable",
  },
  {
    cameraPosition: [-2.7, -0.35, -4.8],
    displayName: "Human Resources",
    id: "human-resources-management",
    labelPosition: {
      compact: [27, 68],
      desktop: [34, 71],
      portrait: [29, 69],
    },
    name: "Human Resources Management",
    palette: {
      core: "#f5f6ff",
      halo: "#8d9ec3",
      orbit: "#6c7892",
    },
    position: [-2.7, -0.6, -9.2],
    schedule: [
      {
        day: "wednesday",
        endTime: "16:30",
        group: "M31",
        room: "E127",
        startTime: "14:30",
      },
      {
        day: "friday",
        endTime: "16:30",
        group: "M31",
        room: "E143",
        startTime: "14:30",
      },
    ],
    scale: 0.76,
    seed: 94_207,
    sourceName: "Gestión de Recursos Humanos",
    status: "explorable",
  },
  {
    cameraPosition: [-1.45, -1.05, -4.9],
    displayName: "Final Project",
    id: "final-project",
    labelPosition: {
      compact: [50, 80],
      desktop: [50, 82],
      portrait: [51, 79],
    },
    name: "Final Project",
    palette: {
      core: "#fff9ea",
      halo: "#d6b56f",
      orbit: "#9f8351",
    },
    position: [-1.45, -1.3, -9.6],
    schedule: [],
    scale: 0.88,
    seed: 72_511,
    sourceName: "Final Project",
    status: "explorable",
  },
] as const satisfies readonly CourseSystemDefinition[];

export const logisticsCourseSystem = universityCourseSystems[0];
