import type { CourseSystemDefinition } from "./course-system-definition";

export const universityCourseSystems = [
  {
    cameraPosition: [-1.72, 1.34, -6.05],
    displayName: "Logistics & Distribution",
    id: "logistics",
    labelPosition: {
      compact: [24, 48],
      desktop: [36.5, 48],
      portrait: [25, 48],
    },
    name: "Logistics and Distribution",
    palette: {
      core: "#f3fbff",
      halo: "#78c8ff",
      orbit: "#79aeea",
    },
    position: [-2.1, 1.15, -8.15],
    schedule: [
      {
        day: "monday",
        endTime: "18:30",
        group: "M41",
        room: "E133",
        startTime: "16:30",
      },
      {
        day: "wednesday",
        endTime: "18:30",
        group: "M41",
        room: "E121",
        startTime: "16:30",
      },
    ],
    scale: 1,
    seed: 81_732,
    sourceName: "Distribución Logística",
    status: "explorable",
  },
  {
    cameraPosition: [-0.5, 1.65, -6.5],
    displayName: "Business Ethics",
    id: "business-ethics",
    labelPosition: {
      compact: [75, 41],
      desktop: [62, 40],
      portrait: [74, 41],
    },
    name: "International Business Ethics",
    palette: {
      core: "#edf6ff",
      halo: "#9895d8",
      orbit: "#7778aa",
    },
    position: [-0.75, 1.45, -8.65],
    schedule: [
      {
        day: "monday",
        endTime: "20:30",
        group: "M41",
        room: "E123",
        startTime: "18:30",
      },
      {
        day: "tuesday",
        endTime: "20:30",
        group: "M41",
        room: "E125",
        startTime: "18:30",
      },
    ],
    scale: 0.78,
    seed: 26_104,
    sourceName: "Ética en los Negocios Internacionales",
    status: "future",
  },
  {
    cameraPosition: [-0.9, 0.45, -6.3],
    displayName: "Language A III",
    id: "language-a-iii",
    labelPosition: {
      compact: [68, 66],
      desktop: [55, 76],
      portrait: [61, 70],
    },
    name: "Language A III",
    palette: {
      core: "#eefeff",
      halo: "#64bac8",
      orbit: "#548a96",
    },
    position: [-1.15, 0.25, -8.45],
    schedule: [
      {
        day: "tuesday",
        endTime: "16:30",
        group: "M33",
        room: "E132",
        startTime: "14:30",
      },
      {
        day: "friday",
        endTime: "16:30",
        group: "M33",
        room: "E032",
        startTime: "14:30",
      },
    ],
    scale: 0.7,
    seed: 59_133,
    sourceName: "Idioma A III",
    status: "future",
  },
  {
    cameraPosition: [-1.9, 0.6, -6.9],
    displayName: "Human Resources",
    id: "human-resources-management",
    labelPosition: {
      compact: [24, 62],
      desktop: [39, 66],
      portrait: [27, 62],
    },
    name: "Human Resources Management",
    palette: {
      core: "#f5f6ff",
      halo: "#8d9ec3",
      orbit: "#6c7892",
    },
    position: [-2.2, 0.45, -9.05],
    schedule: [
      {
        day: "wednesday",
        endTime: "16:30",
        group: "M31",
        room: "E127",
        startTime: "14:30",
      },
      {
        day: "friday",
        endTime: "16:30",
        group: "M31",
        room: "E143",
        startTime: "14:30",
      },
    ],
    scale: 0.66,
    seed: 94_207,
    sourceName: "Gestión de Recursos Humanos",
    status: "future",
  },
  {
    cameraPosition: [0.18, 0.82, -6.55],
    displayName: "Final Project",
    id: "final-project",
    labelPosition: {
      compact: [50, 78],
      desktop: [70, 58],
      portrait: [74, 57],
    },
    name: "Final Project",
    palette: {
      core: "#fff9ea",
      halo: "#d6b56f",
      orbit: "#9f8351",
    },
    position: [0.05, 0.7, -9.1],
    schedule: [],
    scale: 0.82,
    seed: 72_511,
    sourceName: "Final Project",
    status: "future",
  },
] as const satisfies readonly CourseSystemDefinition[];

export const logisticsCourseSystem = universityCourseSystems[0];
